
## Install jupyterhub 
FROM jupyterhub/jupyterhub:0.9.2

## Install dummy-authenticator and dockerspawner
RUN pip install dockerspawner && pip install jupyterhub-dummyauthenticator 

## Install mysql-connector-python
RUN pip install mysql-connector-python

## Install pymysql
RUN pip install PyMySQL






